---
apiVersion: v1
kind: Template
labels:
  app: ocp-storage-generator
  template: ocp-storage-generator-template
message: nope
metadata:
  annotations:
    description: nope
  name: ocp-storage-generator
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${NAME}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${NAME}"
  spec:
    initContainers:
    - name: ocp-storage-generator-init
      image: registry.access.redhat.com/ubi7/ubi-init:latest
      env:
      - name: VOLUME_CAPACITY
        value: ${VOLUME_CAPACITY}
      command:
      - "/bin/bash"
      - "-c"
      - |-
        set -ex
        MEGABYTES=$(( $(echo "${VOLUME_CAPACITY}" | sed -e 's/Gi//') * 1024 ))
        export SIZE=$(( ${MEGABYTES} - 10 ))
        dd if=/dev/zero of=/mydata/file count=${SIZE} bs=1M status=progress
        echo 'Finished'
        exit 0
      volumeMounts:
      - name: "${NAME}"
        mountPath: "/mydata"
    containers:
    - image: quay.io/crio/pause:latest
      name: ocp-storage-generator
    volumes:
    - name: "${NAME}"
      persistentVolumeClaim:
        claimName: "${NAME}"
parameters:
- description: The name assigned to all the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: ocp-storage-generator
- description: Volume space available for data in Gi (min 1Gi)
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
